# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

greedy_stacker <- function(y, Z, metric = 'S', max_iter = 100L) {
    .Call(`_stack_greedy_stacker`, y, Z, metric, max_iter)
}

popping_stacker <- function(y, Z, metric = 'S', max_iter = 100L, popping_rate = 0.03) {
    .Call(`_stack_popping_stacker`, y, Z, metric, max_iter, popping_rate)
}

averaged_popping_stacker <- function(y, Z, metric = 'S', max_iter = 100L, popping_rate = 0.03, repetitions = 100L) {
    .Call(`_stack_averaged_popping_stacker`, y, Z, metric, max_iter, popping_rate, repetitions)
}

